config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :donors ,only: [:create]
  post '/available'=> 'donors#index'

end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/donor.rb
class Donor < ActiveRecord::Base


  validates :name, :presence => {:message=>"الرجاء ادخال الاسم"}
  validates :email , :presence => {:message=>"الرجاء ادخال البريد الالكتروني"}
  validates :blood_type,:presence => {:message=>"الرجاء تحديد فصيلة الدم"}
  validates :city,:presence => {:message=>"الرجاء تحديد ولاية الاقامة"}
  validates :phone_number , :presence => {:message=>"الرجاء ادخال رقم الهاتف"}

  def self.search(donor_blood,donor_city)
    where(['blood_type = ? AND city = ?', donor_blood, donor_city])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController

  def new
    @donor=Donor.new
  end

  def create
    @donor=Donor.new(donor_params)
    if @donor.save
      flash[:success] = "تم تسجيل متبرع جديد ,شكرا لك"
      redirect_to root_path
    else
      if @donor.errors
        session[:errors]=@donor.errors
      end
      flash[:error] = ": لقد حدث خطا ,الرجاء تصحيحه"
      redirect_to root_path
    end
  end


  def index
    donor_city=params[:don_city]
    donor_blood=params[:don_blood]
    @donors=Donor.search(donor_blood,donor_city)
  end


  private

  def donor_params
    params.require(:donor).permit(:name,:blood_type,:phone_number,:city,:email)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @donor=Donor.new
    @donors=Donor.all
    if session[:errors]
      session[:errors].each {|error, error_message| @donor.errors.add error, error_message}
      session.delete :errors
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/donors/index.html.erb
<div class="row center-align">
  <h1>قائمة المتبرعين</h1>
</div>
<div id="contain">
  <div class="row">
    <div class="col s12 m12 offset-l2 l8 z-depth-1-half" id="results">
      <div class="row">
        <% if @donors.any? %>
            <% @donors.each do |donor| %>
                <div class="col s12 m12 waves-effect single-donor" >
                  <span class="dn"> <%= donor.name %> </span>
                  <span class="dp"> <%= donor.phone_number%></span>
                </div>
            <% end %>
        <% else %>
            <div class="col s12 m12 waves-effect single-donor center-align" >
              <span class="dn"> للاسف لا يوجد اي متبرعين</span>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div id="contain">
  <div class="row">

    <% flash.each do |name, msg| %>
        <div class="col s12 m12 l8 offset-l2 z-depth-2 message <%=name %>">
          <%= content_tag :div, msg%>
          <% if @donor.errors.any? %>
              <% @donor.errors.messages.values.each do |message| %>
                  <%message.each do  |m| %>
                    <div><%= m.to_sentence() %>-</div>
                  <% end %>
              <% end %>
          <% end %>
        </div>
    <% end %>

    <%=form_tag "/available",:method => "post" do %>
        <div class="col s12 m12 l8 offset-l2 z-depth-2" id="search-card">
          <div class="row valign center-align">
            <div class="input-field col s12 m12 l6">
              <%= select_tag(:don_blood, options_for_select([["A+","A+"],["A-","A-"],["B+","B+"],["B-","B-"],["O+","O+"],["O-","O-"],["AB+","AB+"],["AB-","AB-"]]),{prompt: 'فصيلة الدم',required: true}) %>
              <label>فصيلة الدم</label>
            </div>
            <div class="input-field col s12 m12 l6">
              <%= select_tag(:don_city,options_for_select( City.all.collect {|city| [ city.name, city.id ] }),{prompt: 'اختر ولايتك',required: true}) %>
              <label>الولاية</label>
            </div>
            <div class="row">
              <button class="btn waves-effect waves-light" type="submit" name="action">بحث</button>
            </div>
          </div>
        </div>
        </div>
    <% end %>

    <div class="row">
      <div class="col s12  m12 l8 offset-l2 z-depth-1-half" id="register-card">
        <div class="row">
          <%= form_for Donor.new ,:html => {:class =>"col s12"} ,:url => donors_path do |f| %>
              <div class="row">
                <div class="input-field col s12">
                  <i class="material-icons prefix mdi-action-account-circle"></i>
                  <%= f.text_field :name,:type=>"text",:class=>"validate" %>
                  <%= f.label :name,"الاسم" %>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <i class="material-icons prefix mdi-communication-phone"></i>
                  <%= f.text_field :phone_number,:type=>"number" ,:class=>"numericOnly validate" %>
                  <%= f.label :phone_number , "رقم الهاتف" %>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <%= f.select(:city, City.all.collect {|city| [ city.name, city.id ] },{prompt: 'اختر ولايتك'}) %>
                  <label>الولاية</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <i class="material-icons prefix action"></i>
                  <%= f.select(:blood_type, options_for_select([["A+","A+"],["A-","A-"],["B+","B+"],["B-","B-"],["O+","O+"],["O-","O-"],["AB+","AB+"],["AB-","AB-"]]),{prompt: 'فصيلة الدم'}) %>
                  <label>فصيلة الدم</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <i class="material-icons prefix mdi-communication-email"></i>
                  <%= f.text_field :email,:type=>"email",:class=>"validate" %>
                  <%= f.label :email,"البريد الالكتروني" %>
                </div>
              </div>
              <div class="row center-align">
                <%= f.submit "تسجيل متبرع جديد" ,:class=>"btn"%>
              </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
            <div class="col s12  m12 l8 offset-l2 z-depth-1-half " id="stats">
              <table class="centered">
                <thead>
                <tr>
                  <th data-field="A+">A+</th>
                  <th data-field="A-">A-</th>
                  <th data-field="B+">B+</th>
                  <th data-field="B-">B-</th>
                  <th data-field="O+">O+</th>
                  <th data-field="O-">O-</th>
                  <th data-field="AB+">AB+</th>
                  <th data-field="AB-">AB-</th>
                </tr>
                </thead>

                <tbody>
                <tr>
                  <td><%= @donors.where(:blood_type=>'A+').count %></td>
                  <td><%= @donors.where(:blood_type=>'A-').count %></td>
                  <td><%= @donors.where(:blood_type=>'B+').count %></td>
                  <td><%= @donors.where(:blood_type=>'B-').count %></td>
                  <td><%= @donors.where(:blood_type=>'O+').count %></td>
                  <td><%= @donors.where(:blood_type=>'O-').count %></td>
                  <td><%= @donors.where(:blood_type=>'AB+').count %></td>
                  <td><%= @donors.where(:blood_type=>'AB-').count %></td>
                </tr>
                </tbody>
              </table>

            </div>
    </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer " style="background-color: #00bcd6">
  <div class="footer-copyright">
    <div class="container center-align">
      © <%= Time.now.year %> برنامج مفتوح المصدر
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>دليل المتبرعين الوطني</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-64675031-2', 'auto');
      ga('send', 'pageview');

  </script>
</head>
<body>
<main>
  <%= yield %>
</main>
<%= render 'layouts/footer' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>